# Generated by Django 3.2.8 on 2021-10-22 15:01

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number not validated.', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')])),
                ('default_pwd', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('regToken', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('profile_photo', models.ImageField(blank=True, null=True, unique=True, upload_to='profilePhoto/', verbose_name='profile photo')),
                ('payment_status', models.CharField(choices=[('S', 'Staff'), ('H', 'Home Owner')], default='H', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False, verbose_name='House ID')),
                ('street_info', models.CharField(max_length=80, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desription', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(unique=True, upload_to='housePhotos/'), size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_approver', to=settings.AUTH_USER_MODEL)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_info', to='cvapp.houseinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='payment id')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_proof', models.ImageField(unique=True, upload_to='paymentProof/', verbose_name='proof of payment')),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housePay_info', to='cvapp.houseinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homePay_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userhouse',
            constraint=models.UniqueConstraint(fields=('user_id', 'home_id'), name='unique_homeOwner'),
        ),
    ]
