# Generated by Django 3.2.8 on 2021-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='progress',
            field=models.IntegerField(default=10, unique=True),
            preserve_default=False,
        ),
    ]
