# Generated by Django 3.2.8 on 2021-10-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payment_status',
            new_name='user_role',
        ),
    ]
