# Generated by Django 3.2.8 on 2021-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_houseinfo_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
