# Generated by Django 3.2.8 on 2021-10-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_rename_payment_status_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
