# Generated by Django 3.2.8 on 2021-10-22 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(unique=True, upload_to='img/housePhotos/'), size=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(unique=True, upload_to='img/paymentProof/', verbose_name='proof of payment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='img/profilePhoto/', verbose_name='profile photo'),
        ),
    ]
