# Generated by Django 3.2.8 on 2021-11-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_alter_houseinfo_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseinfo',
            old_name='street_info',
            new_name='title',
        ),
    ]
