# Generated by Django 3.2.8 on 2021-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_rename_street_info_houseinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='images',
            field=models.ImageField(unique=True, upload_to='img/housePhotos/'),
        ),
    ]
