# Generated by Django 3.2.8 on 2021-10-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_auto_20211022_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
