# Generated by Django 3.2.8 on 2021-11-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0005_auto_20211109_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_add', to=settings.AUTH_USER_MODEL),
        ),
    ]
