# Generated by Django 3.2.8 on 2021-11-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0005_remove_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
