# Generated by Django 3.2.8 on 2021-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='dateUpdated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='userhouse',
            old_name='dateUpdated',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(),
        ),
    ]
