# Generated by Django 3.2.8 on 2021-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_alter_houseinfo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_by',
            field=models.CharField(default=22, max_length=150),
            preserve_default=False,
        ),
    ]
