# Generated by Django 3.2.8 on 2021-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_auto_20211104_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('D', 'Declined'), ('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2),
        ),
    ]
