# Generated by Django 3.2.8 on 2021-11-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_user_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='update_images',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='img/ProjectUpdate/'),
        ),
    ]
