# Generated by Django 3.2.8 on 2021-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0008_alter_projectupdate_update_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(unique=True, upload_to='featurePosts/'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='images',
            field=models.ImageField(unique=True, upload_to='housePhotos/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(unique=True, upload_to='paymentProof/', verbose_name='proof of payment'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='update_images',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='ProjectUpdate/'),
        ),
    ]
